### ISSUE TITLE
separate general-purpose library

### ISSUE THREAD

**Issue by samoht** [samoht/assemblage#56]
For instance, `As_makefile` could be separated in(i)  a proper independent library for generating Makefile, and (ii) the conversion from `As_project.t` to makefiles. The code is already very well separated, it is just a matter of creating an independent package for the Makefile format.

Could be done as well with `As_ocaml`, `As_opam` and `As_ocamlfind` if we really want to.

**Comment by dbuenzli** [comment]
I think most of the *really* general purpose things have been forked off. Closing this to make that issue counter go down.
